#include "tiny_compiler.h"

void compile(const char* source) {
    init_lexer(source);
    current_token = get_next_token();
    
    ASTNode* ast = program();
    generate_program(ast);
    
    printf("Generated bytecode (%d instructions)\n", code_buffer.size);
    print_bytecode(code_buffer.code, code_buffer.size);
    
    printf("\nProgram output:\n");
    run_vm(code_buffer.code, code_buffer.size, num_globals);
}

void print_bytecode(Instruction* code, int size) {
    for (int i = 0; i < size; i++) {
        printf("%4d: ", i);
        switch (code[i].op) {
            case OP_PUSH: printf("PUSH %d\n", code[i].operand); break;
            case OP_STORE: printf("STORE %d\n", code[i].operand); break;
            case OP_LOAD: printf("LOAD %d\n", code[i].operand); break;
            case OP_ADD: printf("ADD\n"); break;
            case OP_SUB: printf("SUB\n"); break;
            case OP_MUL: printf("MUL\n"); break;
            case OP_DIV: printf("DIV\n"); break;
            case OP_PRINT: printf("PRINT\n"); break;
            case OP_PRINT_STR: printf("PRINT_STR %s\n", (char*)code[i].operand); break;
            case OP_JMP: printf("JMP %d\n", code[i].operand); break;
            case OP_JMP_IF: printf("JMP_IF %d\n", code[i].operand); break;
            case OP_HALT: printf("HALT\n"); break;
            default: printf("UNKNOWN\n");
        }
    }
}

int main() {
    const char* test_program = 
        "func main() {"
        "   var x: int = 42;"
        "   var y: int = 100;"
        "   if (x < y) {"
        "       print(\"x is less than y, value: \");"
        "       print(x);"
        "   }"
        "   print(\"\\n\");"
        "   var i: int = 0;"
        "   while (i < 5) {"
        "       print(\"Loop: \");"
        "       print(i);"
        "       print(\"\\n\");"
        "       i = i + 1;"
        "   }"
        "}";
    
    compile(test_program);
    return 0;
}